version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
     - ./pgdata:/var/lib/postgresql/data
     - ./initdb.d/:/docker-entrypoint-initdb.d
    ports:
     - "5433:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
  sonarqube:
    image: qaprosoft/sonarqube:1.0
    ports:
     - "9000:9000"
     - "9002:9002"
    command: -Dsonar.web.context=/sonarqube
    environment:
     - SONARQUBE_JDBC_USERNAME=postgres
     - SONARQUBE_JDBC_PASSWORD=postgres
     - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
     - "db"
