version: '3'
networks:
  default:
    external:
      name: qps-infra
services:
  sonarqube:
    image: qaprosoft/sonarqube:${TAG_SONAR}
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions
    ports:
     - "9000:9000"
     - "9002:9002"
