version: '3'

services:
  sonarqube:
    image: qaprosoft/sonarqube:1.0
    command: -Dsonar.web.context=/sonarqube
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions
    ports:
     - "9000:9000"
     - "9002:9002"
