version: '3.7'
networks:
  default:
    external:
      name: qps-infra
services:
  sonarqube:
    image: qaprosoft/sonarqube:${TAG_SONAR}
    container_name: qps-sonarqube
    # https://jira.sonarsource.com/browse/SONAR-13272 bug with SONAR_WEB_CONTEXT env variable
    command: -Dsonar.web.context=/sonarqube
    volumes:
      - sonarqube-data-volume:/opt/sonarqube/data:rw
      - sonarqube-logs-volume:/opt/sonarqube/logs:rw
      - sonarqube-extensions-volume:/opt/sonarqube/extensions:rw
    ports:
     - "9000:9000"
volumes:
  sonarqube-data-volume:
  sonarqube-logs-volume:
  sonarqube-extensions-volume:

